# Generated by Django 4.0.5 on 2022-12-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_activitystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activity_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.activitystatus'),
        ),
    ]
