# Generated by Django 4.0.5 on 2022-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_anime_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test', max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='premiere_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='base.genre'),
        ),
    ]
