# Generated by Django 4.0.5 on 2022-10-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_anime_watchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListofAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anime')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='test_table',
            field=models.ManyToManyField(to='base.listofanime'),
        ),
    ]
