# Generated by Django 4.0.5 on 2022-10-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_listofanime_user_test_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_table',
        ),
        migrations.DeleteModel(
            name='ListofAnime',
        ),
    ]
