# Generated by Django 4.0.5 on 2022-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_genre_anime_premiere_date_anime_title_anime_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.ManyToManyField(to='base.genre')),
            ],
        ),
    ]
