# Generated by Django 4.0.5 on 2022-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_activities_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='title_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
