# Generated by Django 4.0.5 on 2022-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
