# Generated by Django 4.0.5 on 2022-10-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_watchliststatus_userwatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan_readlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_watchlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='readlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
