# Generated by Django 4.0.5 on 2022-09-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_anime_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='diplay_name',
            new_name='display_name',
        ),
    ]
