# Generated by Django 4.0.5 on 2022-10-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_plan_readlist_remove_user_plan_watchlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwatchlist',
            old_name='anime_id',
            new_name='animeid',
        ),
        migrations.RenameField(
            model_name='userwatchlist',
            old_name='user_id',
            new_name='userid',
        ),
    ]
