# Generated by Django 4.0.5 on 2022-09-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_readlist_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='readlist',
        ),
    ]
