# Generated by Django 4.0.5 on 2022-10-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_anime_id_userwatchlist_animeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwatchlist',
            old_name='animeid',
            new_name='anime',
        ),
        migrations.RenameField(
            model_name='userwatchlist',
            old_name='userid',
            new_name='user',
        ),
    ]
