# Generated by Django 4.0.5 on 2022-09-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_user_readlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='readlist',
            field=models.ManyToManyField(to='base.manga'),
        ),
    ]
