# Generated by Django 4.0.5 on 2022-10-18 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_animeid_userwatchlist_anime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadlistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserReadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.manga')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.readliststatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
