# Generated by Django 4.0.5 on 2022-09-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_readlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='readlist',
            field=models.ManyToManyField(blank=True, null=True, to='base.manga'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, to='base.anime'),
        ),
    ]
