# Generated by Django 4.0.5 on 2022-09-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_readlist_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='readlist',
            field=models.ManyToManyField(blank=True, to='base.manga'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='base.anime'),
        ),
    ]
