# Generated by Django 4.0.5 on 2022-10-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_friendship_alter_userreadlist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreadlist',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.readliststatus'),
        ),
        migrations.AlterField(
            model_name='userwatchlist',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.watchliststatus'),
        ),
    ]
