# Generated by Django 4.0.5 on 2022-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_author_works_author_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='author_work', to='base.manga'),
        ),
        migrations.CreateModel(
            name='StudioCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=60)),
                ('anime_works', models.ManyToManyField(blank=True, to='base.anime')),
            ],
        ),
    ]
