# Generated by Django 4.0.5 on 2022-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_public_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
