# Generated by Django 4.0.5 on 2022-09-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_anime_genre_alter_anime_premiere_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='premiere_date',
        ),
    ]
