# Generated by Django 4.0.5 on 2022-12-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_userreadlist_created_userreadlist_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
    ]
