# Generated by Django 4.0.5 on 2022-09-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_anime_genre_remove_anime_premiere_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(default=None, to='base.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='premiere_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
