# Generated by Django 4.0.5 on 2022-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_anime_genre_anime_premiere_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='thumbnail',
            field=models.URLField(default=None, null=True),
        ),
    ]
