# Generated by Django 4.0.5 on 2022-12-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_activitytype_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='isAnime',
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.activitytype'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
