# Generated by Django 4.0.5 on 2022-10-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_anime_large_image_alter_anime_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
