# Generated by Django 4.0.5 on 2022-12-03 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_activities_isanime_activities_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
