# Generated by Django 4.0.5 on 2022-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_activities_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
