# Generated by Django 4.0.5 on 2022-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_activities_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_public_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='https://res.cloudinary.com/dg1bym3ax/image/upload/v1669651547/blank-avatar.jpg', null=True),
        ),
    ]
