# Generated by Django 4.0.5 on 2022-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_mangagenre_rename_genre_animegenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='summary',
            field=models.TextField(default='No summary'),
        ),
        migrations.AddField(
            model_name='manga',
            name='summary',
            field=models.TextField(default='No summary'),
        ),
    ]
