# Generated by Django 4.0.5 on 2022-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_user_avatar_public_id_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(default='No intro.', null=True),
        ),
    ]
