# Generated by Django 4.0.5 on 2022-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_anime_summary_manga_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='premiere_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
