# Generated by Django 4.0.5 on 2022-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_anime_genre_manga_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dropped_readlist',
            field=models.ManyToManyField(blank=True, related_name='droppedlist_read', to='base.manga'),
        ),
        migrations.AddField(
            model_name='user',
            name='dropped_watchlist',
            field=models.ManyToManyField(blank=True, related_name='droppedlist_watch', to='base.anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_readlist',
            field=models.ManyToManyField(blank=True, related_name='plantoread', to='base.manga'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_watchlist',
            field=models.ManyToManyField(blank=True, related_name='plantowatch', to='base.anime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='readlist',
            field=models.ManyToManyField(blank=True, related_name='readlist', to='base.manga'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='base.anime'),
        ),
    ]
